openapi: 3.2.0
info:
  title: Locus Shift Tag API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: ShiftTag
paths:
  /client/{clientId}/shift-manager/{tagId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/TagIdParam'
    get:
      summary: fetch shiftTag by id
      operationId: getShiftTag
      parameters:
      - name: include
        in: query
        description: Extra fields that should be returned.
        schema:
          type: string
      tags:
      - ShiftTag
      responses:
        '200':
          description: ShiftTag object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShiftTag'
      security:
      - locusauth: []
    put:
      summary: Create a given shiftTag
      operationId: createShiftTag
      parameters:
      - $ref: '#/components/parameters/OverwriteParam'
      tags:
      - ShiftTag
      responses:
        '200':
          description: ShiftTag object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShiftTag'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShiftTag'
        description: Create shift tag request
        required: true
  /client/{clientId}/shift-manager/{tagId}/disable:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/TagIdParam'
    post:
      description: Disable a specific Shift Tag
      operationId: disableShiftTag
      tags:
      - ShiftTag
      responses:
        '200':
          description: Updated shiftTag object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShiftTag'
      security:
      - locusauth: []
      summary: Disable shift tag
      x-summary-source: derived
components:
  schemas:
    ShiftTag:
      $ref: https://swagger.locus-api.com/roster-entity.yaml#/definitions/ShiftTag
  parameters:
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
    TagIdParam:
      name: tagId
      in: path
      description: Id of the shiftTag
      required: true
      schema:
        type: string
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
