openapi: 3.2.0
info:
  title: Locus Team Master API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: TeamMaster
paths:
  /client/{clientId}/team-master/{teamId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/TeamIdParam'
    get:
      summary: Get a team
      operationId: getTeam
      parameters:
      - name: include
        in: query
        description: Comma separated list of extra fields that should be returned. Supported values are BUSINESS_UNIT, PREFERENCES.
        schema:
          type: string
      tags:
      - TeamMaster
      responses:
        '200':
          description: team object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
      security:
      - locusauth: []
    put:
      summary: Create a team
      operationId: createTeam
      parameters:
      - $ref: '#/components/parameters/OverwriteParam'
      tags:
      - TeamMaster
      responses:
        '200':
          description: Created team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequest'
        description: Create team request
        required: true
  /client/{clientId}/team-master/{teamId}/status:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/TeamIdParam'
    post:
      description: Update status for a specific team
      operationId: updateTeamStatus
      tags:
      - TeamMaster
      responses:
        '200':
          description: Updated team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityStatusUpdateRequest'
        description: Updated status of team
        required: true
      summary: Update team status
      x-summary-source: derived
components:
  schemas:
    EntityDefinition:
      type: object
    EntityStatusUpdateRequest:
      description: Wrapper for entity status update request
      required:
      - status
      properties:
        status:
          $ref: '#/components/schemas/EntityStatus'
    IndustryType:
      type: object
    CityId:
      description: An id for a city
      required:
      - cityId
      properties:
        cityId:
          type: string
    BusinessUnit:
      description: Business unit of the client
      required:
      - clientId
      - businessUnitId
      - name
      - shortName
      - status
      - version
      properties:
        clientId:
          type: string
        businessUnitId:
          type: string
        name:
          description: Name of business unit
          type: string
        shortName:
          description: Short name of business unit
          type: string
        description:
          description: Description of business unit
          type: string
        status:
          $ref: '#/components/schemas/BusinessUnitStatusEnum'
        industryType:
          $ref: '#/components/schemas/IndustryType'
        color:
          type: string
        version:
          type: integer
          format: int32
    Team:
      description: Team entity
      allOf:
      - $ref: '#/components/schemas/EntityDefinition'
      - type: object
        properties:
          businessUnitId:
            $ref: '#/components/schemas/BusinessUnitId'
          businessUnit:
            $ref: '#/components/schemas/BusinessUnit'
          cityId:
            $ref: '#/components/schemas/CityId'
          color:
            description: Color of the team
            type: string
          shortCode:
            description: unique 4 character identifier for a team
            type: string
    BusinessUnitId:
      required:
      - clientId
      - businessUnitId
      properties:
        clientId:
          type: string
        businessUnitId:
          type: string
    EntityStatus:
      type: object
    CreateTeamRequest:
      description: Team entity create request
      allOf:
      - $ref: '#/components/schemas/EntityDefinition'
      - type: object
        properties:
          businessUnitId:
            $ref: '#/components/schemas/BusinessUnitId'
          cityId:
            $ref: '#/components/schemas/CityId'
          color:
            description: Color of the team
            type: string
    BusinessUnitStatusEnum:
      description: Operational status of the business unit
      type: string
      default: ACTIVE
      enum:
      - ACTIVE
      - INACTIVE
  parameters:
    TeamIdParam:
      name: teamId
      in: path
      description: Id of the team
      required: true
      schema:
        type: string
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
