openapi: 3.2.0
info:
  title: Locus Transporter API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: Transporter
paths:
  /client/{clientId}/transporter/{transporterId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/TransporterIdParam'
    get:
      summary: Get a transporter
      operationId: getTransporter
      parameters:
      - name: include
        in: query
        description: Comma separated list of extra fields that should be returned. Supported values are CONTACT
        required: false
        schema:
          type: string
      tags:
      - Transporter
      responses:
        '200':
          description: transporter object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transporter'
      security:
      - locusauth: []
    put:
      summary: Create a transporter
      operationId: createTransporter
      parameters:
      - $ref: '#/components/parameters/OverwriteParam'
      tags:
      - Transporter
      responses:
        '200':
          description: Created transporter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transporter'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTransporterRequest'
        description: Create transporter request
        required: true
  /client/{clientId}/transporter/{transporterId}/disable:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/TransporterIdParam'
    post:
      description: Disable a specific transporter
      operationId: disableTransporter
      tags:
      - Transporter
      responses:
        '200':
          description: Updated transporter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transporter'
      security:
      - locusauth: []
      summary: Disable transporter
      x-summary-source: derived
components:
  schemas:
    CreateTransporterRequest:
      description: Wrapper for transporter create request
      allOf:
      - $ref: '#/components/schemas/Transporter'
      - type: object
    Transporter:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/Transporter
  parameters:
    TransporterIdParam:
      name: transporterId
      in: path
      description: Id of the transporter
      required: true
      schema:
        type: string
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
