openapi: 3.2.0
info:
  title: Locus Rider API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: Rider
paths:
  /client/{clientId}/rider/{riderId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/RiderIdParam'
    get:
      summary: Get a rider
      operationId: getRider
      parameters:
      - name: include
        in: query
        description: Comma separated list of extra fields that should be returned. Supported values are SHIFTS, SALES_CATEGORIES, RIDER_PERSONA
        required: false
        schema:
          type: string
      tags:
      - Rider
      responses:
        '200':
          description: rider object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
      security:
      - locusauth: []
    put:
      summary: Create a rider
      operationId: createRider
      parameters:
      - $ref: '#/components/parameters/OverwriteParam'
      tags:
      - Rider
      responses:
        '200':
          description: Created rider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRiderRequest'
        description: Create rider request
        required: true
  /client/{clientId}/rider/{riderId}/disable:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/RiderIdParam'
    post:
      description: Disable a specific rider
      operationId: disableRider
      tags:
      - Rider
      responses:
        '200':
          description: Updated rider
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rider'
      security:
      - locusauth: []
      summary: Disable rider
      x-summary-source: derived
components:
  schemas:
    CreateRiderRequest:
      description: Wrapper for rider create request
      allOf:
      - $ref: '#/components/schemas/Rider'
      - type: object
        properties:
          retainAuth:
            description: Boolean to indicate if Auth should be retained if already generated
            type: boolean
            default: true
    Rider:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/Rider
  parameters:
    RiderIdParam:
      name: riderId
      in: path
      description: Id of the rider
      required: true
      schema:
        type: string
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
