openapi: 3.2.0
info:
  title: Locus Roster API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: Roster
paths:
  /client/{clientId}/roster/{rosterId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/RosterIdParam'
    get:
      summary: Get Roster by Id
      operationId: getRoster
      parameters:
      - name: include
        in: query
        description: Comma separated list of extra fields that should be returned. Supported values are RESOURCES.
        required: false
        schema:
          type: string
      tags:
      - Roster
      responses:
        '200':
          description: GetRosterResponse Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRosterResponse'
      security:
      - locusauth: []
  /client/{clientId}/rosters-auto-create:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/OverwriteParam'
    post:
      summary: API Bulk create rosters for api integrated clients
      operationId: createRostersApiRequest
      tags:
      - Roster
      responses:
        '200':
          description: API Bulk create rosters response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRosterResponse'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRostersApiRequest'
        description: Request body for api Integrated clients
        required: true
  /client/{clientId}/roster/{rosterId}/disable:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/RosterIdParam'
    post:
      description: Disable a specific roster
      operationId: disableRoster
      tags:
      - Roster
      responses:
        '200':
          description: Updated roster
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Roster'
      security:
      - locusauth: []
      summary: Disable roster
      x-summary-source: derived
components:
  schemas:
    Roster:
      $ref: https://swagger.locus-api.com/roster-entity.yaml#/definitions/Roster
    CreateRostersApiRequest:
      description: API Roster request for bulk create
      required:
      - clientId
      - startDate
      - endDate
      - entityType
      - teamId
      - riderIds
      - vehicleIds
      - vehicleModelId
      - daysOff
      - shift
      - applyToAll
      properties:
        clientId:
          type: string
        startDate:
          description: Roster start date in YYYY-MM-DD format. Eg. 2021-11-18
          type: string
        endDate:
          description: Roster end date in YYYY-MM-DD format. Eg. 2021-11-18
          type: string
        entityType:
          description: Entity type for the roster
          $ref: '#/components/schemas/RosterEntityType'
        teamId:
          description: Teams id for Roster Creation
          type: string
        riderIds:
          description: List of Riders
          type: array
          items:
            type: string
        vehicleIds:
          description: List of Vehicles
          type: array
          items:
            type: string
        applyToAll:
          type: boolean
          default: false
        vehicleModelId:
          $ref: '#/components/schemas/VehicleModelId'
        daysOff:
          description: List of Days Off for Roster Creation
          type: array
          items:
            type: string
        shift:
          $ref: '#/components/schemas/CreateRosterShiftApiRequest'
        skills:
          type: array
          items:
            $ref: '#/components/schemas/SkillId'
    CreateRosterShiftApiRequest:
      description: Shift Roster request for bulk create
      required:
      - tagId
      - start
      properties:
        tagId:
          description: Shift Tag Id for the Roster
          type: string
        start:
          $ref: '#/components/schemas/RosterShiftLocation'
        end:
          $ref: '#/components/schemas/RosterShiftLocation'
        breaks:
          type: array
          description: List of Breaks for the Roster
          items:
            $ref: '#/components/schemas/CreateBreaksApiRequest'
    CreateRosterResponse:
      $ref: https://swagger.locus-api.com/roster-entity.yaml#/definitions/CreateRosterResponse
    CreateBreaksApiRequest:
      description: Shift Roster request for bulk create
      required:
      - startTime
      - endTime
      - duration
      - breakType
      properties:
        startTime:
          description: Break Start Time
          type: string
        endTime:
          description: Break End Time
          type: string
        duration:
          description: Duration of break
          type: string
        breakType:
          description: Type of break - LUNCH, REFUEL
          type: string
          enum:
          - LUNCH
          - REFUEL
          - NIGHT
          - OTHER
          default: LUNCH
    VehicleModelId:
      type: object
    RosterShiftLocation:
      $ref: https://swagger.locus-api.com/roster-entity.yaml#/definitions/RosterShiftLocation
    RosterEntityType:
      $ref: https://swagger.locus-api.com/roster-entity.yaml#/definitions/RosterEntityType
    SkillId:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/SkillId
    GetRosterResponse:
      $ref: https://swagger.locus-api.com/roster-entity.yaml#/definitions/GetRosterResponse
  parameters:
    RosterIdParam:
      name: rosterId
      in: path
      description: Id of roster
      required: true
      schema:
        type: string
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
