openapi: 3.2.0
info:
  title: Locus Location Master API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: Location Master
paths:
  /client/{clientId}/location/{locationId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/LocationIdParam'
    get:
      summary: Get a location
      operationId: getLocation
      tags:
      - Location Master
      parameters:
      - name: include
        in: query
        description: Comma separated list of extra fields that should be returned. Supported values are CONTACT.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: location object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLocation'
      security:
      - locusauth: []
    put:
      summary: Create a location
      operationId: createLocation
      parameters:
      - $ref: '#/components/parameters/OverwriteParam'
      tags:
      - Location Master
      responses:
        '200':
          description: Created location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLocation'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLocationRequest'
        description: Create location request
        required: true
  /client/{clientId}/location/{locationId}/disable:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/LocationIdParam'
    post:
      description: Disable a specific location
      operationId: disableLocation
      tags:
      - Location Master
      responses:
        '200':
          description: Updated location
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLocation'
      security:
      - locusauth: []
      summary: Disable location
      x-summary-source: derived
components:
  schemas:
    CreateLocationRequest:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/CreateLocationRequest
    MasterLocation:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/MasterLocation
  parameters:
    LocationIdParam:
      name: locationId
      in: path
      description: Id of the location
      required: true
      schema:
        type: string
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
