openapi: 3.2.0
info:
  title: Locus SKU Master API
  description: Manage your deliveries with the Locus API
  version: 1.0.0
tags:
- name: SKU Master
paths:
  /client/{clientId}/lineitem/{lineItemId}:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/LineItemIdParam'
    get:
      summary: Get a line item
      operationId: getLineItem
      tags:
      - SKU Master
      parameters:
      - name: include
        in: query
        description: Comma separated list of extra fields that should be returned. Supported values are LOCATIONS.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Line item object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLineItem'
      security:
      - locusauth: []
    put:
      summary: Create a line item
      operationId: createLineItem
      parameters:
      - $ref: '#/components/parameters/OverwriteParam'
      tags:
      - SKU Master
      responses:
        '200':
          description: Created line item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLineItem'
      security:
      - locusauth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLineItemRequest'
        description: Create line item request
        required: true
  /client/{clientId}/lineitem/{lineItemId}/disable:
    parameters:
    - $ref: '#/components/parameters/ClientIdParam'
    - $ref: '#/components/parameters/LineItemIdParam'
    post:
      description: Disable a specific line item
      operationId: disableLineItem
      tags:
      - SKU Master
      responses:
        '200':
          description: Updated line item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MasterLineItem'
      security:
      - locusauth: []
      summary: Disable line item
      x-summary-source: derived
components:
  schemas:
    CreateLineItemRequest:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/CreateLineItemRequest
    MasterLineItem:
      $ref: https://swagger.locus-api.com/common-entities.yaml#/definitions/MasterLineItem
  parameters:
    LineItemIdParam:
      name: lineItemId
      in: path
      description: Id of the line item
      required: true
      schema:
        type: string
    ClientIdParam:
      name: clientId
      in: path
      description: Id of the client
      required: true
      schema:
        type: string
    OverwriteParam:
      name: overwrite
      in: query
      description: Boolean flag if true, will overwrite the existing entity
      required: false
      schema:
        type: boolean
  securitySchemes:
    locusauth:
      type: http
      scheme: basic
      description: HTTP Basic Authentication
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
